### ISSUE TITLE
Panic while using a proc_macro2 type across crates

### ISSUE THREAD

**Issue by fpoli** [alexcrichton/proc-macro2#188]
Hi! I'm building a library for common transformations on `proc_macro2` types, to be used by crates that implement procedural macros. However, on a simple example I get a "procedural macro API is used outside of a procedural macro" panic while running the procedural macros that use my library. On rustc stable the stacktrace is this:

```
thread '<unnamed>' panicked at 'procedural macro API is used outside of a procedural macro', src/libproc_macro/bridge/client.rs:315:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'procedural macro API is used outside of a procedural macro', src/libproc_macro/bridge/client.rs:315:17
stack backtrace:
   0:     0x7f82cd65bc63 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h39625934646a062b
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x7f82cd6585db - std::sys_common::backtrace::_print::h5ed439e79e04d188
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x7f82cd65b1c6 - std::panicking::default_hook::{{closure}}::h13bf33e40bf761d8
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x7f82cd65af59 - std::panicking::default_hook::h7e24c700cb9d2623
                               at src/libstd/panicking.rs:211
   4:     0x7f82cd65b85f - std::panicking::rust_panic_with_hook::h37915b26028fb081
                               at src/libstd/panicking.rs:474
   5:     0x7f82cd644c54 - std::panicking::begin_panic::hcdc903573ebd5923
                               at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libstd/panicking.rs:408
   6:     0x7f82cd646fe7 - proc_macro::bridge::client::BridgeState::with::{{closure}}::{{closure}}::h3382c8e11e482293
                               at src/libproc_macro/bridge/client.rs:315
                               at src/libproc_macro/bridge/client.rs:285
   7:     0x7f82cd64fa6e - <proc_macro::bridge::client::TokenStream as core::ops::drop::Drop>::drop::h8e51ee09467cd1a5
                               at src/libproc_macro/bridge/scoped_cell.rs:73
                               at src/libproc_macro/bridge/client.rs:283
                               at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libstd/thread/local.rs:299
                               at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libstd/thread/local.rs:245
                               at src/libproc_macro/bridge/client.rs:282
                               at src/libproc_macro/bridge/client.rs:313
                               at src/libproc_macro/bridge/client.rs:229
                               at src/libproc_macro/bridge/client.rs:54
   8:     0x7f82cd4868ee - core::ptr::real_drop_in_place::hf2445d86ec525323
                               at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libcore/ptr.rs:193
   9:     0x7f82cd4843ed - core::ptr::real_drop_in_place::ha7ade299302c3d13
                               at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libcore/ptr.rs:193
  10:     0x7f82cd481996 - core::ptr::real_drop_in_place::h43791beb06c742c8
                               at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libcore/ptr.rs:193
  11:     0x7f82cd485c4d - core::ptr::real_drop_in_place::hd775cf35fc1bb319
                               at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libcore/ptr.rs:193
  12:     0x7f82cd48a9ff - rust_contracts_plugin::add_print_statement::h7dfb1243dcb5f90e
                               at src/lib.rs:45
  13:     0x7f82cd48ade4 - <rust_contracts_plugin::ExamplePlugin as rust_contracts_common::Plugin>::requires::he0ade53953999f6a
                               at src/lib.rs:49
  14:     0x7f82cd94afd5 - rust_contracts::requires::hb06e7b0e59ece6e3
                               at src/lib.rs:20
  15:     0x7f82db5846c3 - std::panicking::try::do_call::he0cfe2347b79c08b
                               at src/libproc_macro/bridge/client.rs:412
                               at src/libproc_macro/bridge/scoped_cell.rs:78
                               at src/libproc_macro/bridge/scoped_cell.rs:73
                               at src/libproc_macro/bridge/scoped_cell.rs:78
                               at src/libproc_macro/bridge/client.rs:309
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:299
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:245
                               at src/libproc_macro/bridge/client.rs:309
                               at src/libproc_macro/bridge/client.rs:404
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  16:     0x7f82dfc8f169 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  17:     0x7f82db589964 - proc_macro::bridge::client::__run_expand2::h06efd32edc9bf6c0
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
                               at src/libproc_macro/bridge/client.rs:403
  18:     0x7f82d8efa2db - proc_macro::bridge::server::run_server::h5ad2e1d5ca69ae92
  19:     0x7f82d8f41bf6 - proc_macro::bridge::server::<impl proc_macro::bridge::client::Client<fn(proc_macro::TokenStream, proc_macro::TokenStream) .> proc_macro::TokenStream>>::run::hc54f284a62bead95
  20:     0x7f82d8f40ae4 - <syntax_ext::proc_macro_impl::AttrProcMacro as syntax::ext::base::AttrProcMacro>::expand::hc796c23e0e298b84
  21:     0x7f82dc450e81 - syntax::ext::expand::MacroExpander::expand_invoc::h83e74a69b56716b3
  22:     0x7f82dc44aaa2 - syntax::ext::expand::MacroExpander::expand_fragment::hde21eab708be7bea
  23:     0x7f82dc449a34 - syntax::ext::expand::MacroExpander::expand_crate::hbae5c9f93d7abb65
  24:     0x7f82deec5e2a - rustc_interface::passes::configure_and_expand_inner::{{closure}}::h6d6c401c52c50a09
  25:     0x7f82deebf85c - rustc::util::common::time::he70e5592d51735a8
  26:     0x7f82dee7ecf1 - rustc_interface::passes::configure_and_expand_inner::hbcddd9e6c04bcc13
  27:     0x7f82def2161d - rustc_interface::passes::configure_and_expand::{{closure}}::heb783aa758c77f92
  28:     0x7f82deeeb541 - rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new::h94ef77888478da3f
  29:     0x7f82dee7bd15 - rustc_interface::passes::configure_and_expand::h55ccdb31ace0623b
  30:     0x7f82dee6893b - rustc_interface::queries::Query<T>::compute::h02f8b9980061120d
  31:     0x7f82dee6b2f2 - rustc_interface::queries::Query<T>::compute::hd767ea13615a6983
  32:     0x7f82dee68195 - rustc_interface::queries::Query<T>::compute::h02d0256bb419922a
  33:     0x7f82def71633 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::prepare_outputs::h1fedf977dc567849
  34:     0x7f82dff689f3 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h01017a6213536cb6
  35:     0x7f82dffe6da5 - std::thread::local::LocalKey<T>::with::h57e4e9c51937ccb9
  36:     0x7f82dff89eb4 - scoped_tls::ScopedKey<T>::set::h581b66761e86975e
  37:     0x7f82dffd5801 - syntax::with_globals::h7a79417414defd1b
  38:     0x7f82dff37414 - std::sys_common::backtrace::__rust_begin_short_backtrace::h81c9d6a59d8e80cf
  39:     0x7f82dfc8f169 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  40:     0x7f82dff62e58 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd1b720554dd4145a
  41:     0x7f82dfc6036e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  42:     0x7f82dfc8dddf - std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
                               at src/libstd/sys_common/thread.rs:13
                               at src/libstd/sys/unix/thread.rs:79
  43:     0x7f82df9ff6b9 - start_thread
  44:     0x7f82df32941c - clone
  45:                0x0 - <unknown>
thread panicked while panicking. aborting.
```

Is this an expected limitation of `proc_macro2` or a bug? In the procedural macro implementation I'm just converting a `proc_macro::TokenStream` to a `proc_macro2::TokenStream`, passing it to the library that I'm building.

**Comment by alexcrichton** [comment]
Could you share the code that leads to this? It's expected to get one of these panics, but the double panic causing an abort is a bug. (I'm not sure how that's happening though)

**Comment by fpoli** [comment]
Sure, the code is here: https://github.com/viperproject/rust-contracts/tree/eea10fae8a7b97a5b64ca3f9efb3038e4a6d9246

To see the crash:
```bash
cargo build --all --examples
cargo build --manifest-path example_plugin/Cargo.toml
LD_LIBRARY_PATH=example_plugin/target/debug/ RUST_CONTRACTS_PLUGIN=example_plugin/target/debug/ cargo test --all --examples -- --nocapture
```

The crate in `example_plugin` is called `rust_contracts_plugin` and is linked as a native library to `rust_contracts` (the main crate).

**Comment by alexcrichton** [comment]
Ok thanks for the info! This is indeed something not supported by this library nor really something that can be supported. [This is basically what's not valid](https://github.com/viperproject/rust-contracts/blob/eea10fae8a7b97a5b64ca3f9efb3038e4a6d9246/common/src/lib.rs#L28) because it's not valid for `TokenStream` to cross dynamic library boundaries as-is.

**Comment by xiandaoyan** [comment]
I have the same questions, while I had upgrade rustlib(libstd, libcore, proc_macro...)，then I recompile fuchsia system, I got the infos:
./host_x64/configc rust --cm obj/src/diagnostics/sampler/cml/sampler-manifest/sampler.cm --output obj/src/diagnostics/sampler/sampler-component-config_rust_config_lib_source.rs --fidl-library-name cf.sc.internal.samplercomponentconfig --rustfmt ../../prebuilt/third_party/rust/linux-x64/bin/rustfmt --rustfmt-config ../../rustfmt.toml

_Illegal instruction (core dumped)_

I tracking my code found the reason is,
fn with<R>(f: impl FnOnce  --> panic!("procedural macro API is used outside of a procedural macro");

How do I resolve this build error?   Could you please help me！
