### ISSUE TITLE
rustc SIGSEGV when compiling proc-macro2 as dependency for ethabi-cli on Raspi Zero W (armv6l)

### ISSUE THREAD

**Issue by dyntaos** [alexcrichton/proc-macro2#208]
When installing ethabi-cli via cargo, proc-macro2 causes rustc to throw a SIGSEGV. This very well may be a rustc issue, but I figured this was a better place to start in seeking a solution.

This is on a Raspi Zero W (armv6l) running Raspbian (output of uname below). In fact I have 2 of these devices, both with the same packages installed and with the same issues.

I installed Rust from the website, rather than apt.

```
pi@spark1:~ $ cargo install ethabi-cli
    Updating crates.io index
  Installing ethabi-cli v9.0.1
   Compiling proc-macro2 v1.0.6
error: failed to compile 'ethabi-cli v9.0.1', intermediate artifacts can be found at '/tmp/cargo-installnTobz7'

Caused by:
  could not compile 'proc-macro2'.

Caused by:
  process didn't exit successfully: 'rustc --edition=2018 --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.6/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=54027d3f099db413 -C extra-filename=-54027d3f099db413 --out-dir /tmp/cargo-installnTobz7/release/build/proc-macro2-54027d3f099db413 -L dependency=/tmp/cargo-installnTobz7/release/deps --cap-lints allow' (signal: 11, SIGSEGV: invalid memory reference)

pi@spark1:~ $ rustc --version
rustc 1.40.0 (73528e339 2019-12-16)

pi@spark1:~ $ cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)

pi@spark1:~ $ uname -a
Linux spark1 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux
```

**Comment by dyntaos** [comment]
I have just tested this on a different armv6l machine (/proc/cpuinfo below), with the same _exact_ error message as listed above:

`processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 000e
Serial          : 0000000006191449
Model           : Raspberry Pi Model B Rev 2
`

`****@****:~$ rustc --version
rustc 1.40.0 (73528e339 2019-12-16)
****@****:~$ cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)
`

**Comment by dyntaos** [comment]
I re-ran the the compilation on the Raspi Zero W's in GDB, backtrace below. I am thinking this should go to the rustc maintainers, thoughts?

```
Thread 21 "rustc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xac1fd100 (LWP 655)]
0xb01c1114 in void std::__insertion_sort<__gnu_cxx::__normal_iterator<std::pair<unsigned long long, llvm::Function*>*, std::vector<std::pair<unsigned long long, llvm::Function*>, std::allocator<std::pair<unsigned long long, llvm::Function*> > > >, __gnu_cxx::__ops::_Iter_comp_iter<llvm::less_first> >(__gnu_cxx::__normal_iterator<std::pair<unsigned long long, llvm::Function*>*, std::vector<std::pair<unsigned long long, llvm::Function*>, std::allocator<std::pair<unsigned long long, llvm::Function*> > > >, __gnu_cxx::__normal_iterator<std::pair<unsigned long long, llvm::Function*>*, std::vector<std::pair<unsigned long long, llvm::Function*>, std::allocator<std::pair<unsigned long long, llvm::Function*> > > >, __gnu_cxx::__ops::_Iter_comp_iter<llvm::less_first>) ()
   from /home/pi/.rustup/toolchains/stable-arm-unknown-linux-gnueabihf/lib/rustlib/arm-unknown-linux-gnueabihf/codegen-backends/librustc_codegen_llvm-llvm.so
(gdb) bt full
#0  0xb01c1114 in void std::__insertion_sort<__gnu_cxx::__normal_iterator<std::pair<unsigned long long, llvm::Function*>*, std::vector<std::pair<unsigned long long, llvm::Function*>, std::allocator<std::pair<unsigned long long, llvm::Function*> > > >, __gnu_cxx::__ops::_Iter_comp_iter<llvm::less_first> >(__gnu_cxx::__normal_iterator<std::pair<unsigned long long, llvm::Function*>*, std::vector<std::pair<unsigned long long, llvm::Function*>, std::allocator<std::pair<unsigned long long, llvm::Function*> > > >, __gnu_cxx::__normal_iterator<std::pair<unsigned long long, llvm::Function*>*, std::vector<std::pair<unsigned long long, llvm::Function*>, std::allocator<std::pair<unsigned long long, llvm::Function*> > > >, __gnu_cxx::__ops::_Iter_comp_iter<llvm::less_first>) ()
   from /home/pi/.rustup/toolchains/stable-arm-unknown-linux-gnueabihf/lib/rustlib/arm-unknown-linux-gnueabihf/codegen-backends/librustc_codegen_llvm-llvm.so
No symbol table info available.
#1  0x004f3008 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by dyntaos** [comment]
Compiling proc-macro2 as well as ethabi from their repos using `cargo build --verbose` worked. I am unsure why this resulted in rustc segfaulting when using `cargo install`.

**Comment by peter-lyons-kehl** [comment]
Potentially related to https://github.com/dtolnay/no-panic/issues/77 (on `x86_64-unknown-linux-gnu`, four different versions).

@Dyntaos Has this problem ever resolved? I don't normally use same targets as you've used here. Did you get/install the targets in any special way, and/or do you have any special global Rust/Cargo config?
